receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

#extensions:
#  health_check:
#    endpoint: 0.0.0.0:13133

exporters:
  prometheusremotewrite:
    endpoint: "http://victoria-metrics:8428/api/v1/write"

  jaeger:
    endpoint: "http://jaeger:14250"
    tls:
      insecure: true

  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    logs_index: "otel-logs-%{+yyyy.mm.dd}"   # Index for logs

  logging:
    loglevel: debug

service:
  telemetry:
    logs:
      level: info
#  extensions: [health_check]
  pipelines:
    traces: # Pipeline for Traces #
      receivers: [otlp]
      exporters: [jaeger, logging]                    # Send traces to Jaeger & Elasticsearch

    metrics: # Pipeline for Metrics #
      receivers: [otlp]
      exporters: [prometheusremotewrite, logging]     # Send metrics to Prometheus

    logs: # Pipeline for Logs #
      receivers: [otlp]
      exporters: [elasticsearch, logging]             # Send logs to Elasticsearch
